version: '3'
services: 
  mongodb:
    image: mongo
    container_name: 'seraphini-container-db'
    environment:
      - MONGO_INITDB_DATABASE=seraphini-db
      - MONGO_INITDB_ROOT_USERNAME=Mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - '27017-27019:27017-27019'
