name: Demo GitHub Actions
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 17.x
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - name: Install dependencies
        run: yarn
      - name:
        cmd: yarn jest

      - name: Code Coverage
        uses: codecov/codecov-action@v1
